// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUFnSZw_G0ykM26q02Qlz4UMTQH9gQ64w',
    appId: '1:96147049865:web:e4a9fffb6d4cd73297a558',
    messagingSenderId: '96147049865',
    projectId: 'ecommerce-app-bf2fc',
    authDomain: 'ecommerce-app-bf2fc.firebaseapp.com',
    storageBucket: 'ecommerce-app-bf2fc.appspot.com',
    measurementId: 'G-9XFGZB307D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaZHk-8QXexDktSrH0DsjoJYmqM68wSkM',
    appId: '1:96147049865:android:24220331b2644d8597a558',
    messagingSenderId: '96147049865',
    projectId: 'ecommerce-app-bf2fc',
    storageBucket: 'ecommerce-app-bf2fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXC4f640O3zD3xkSbGQAXUlkFbOWp6TFE',
    appId: '1:96147049865:ios:a9ae3d0c55756b1897a558',
    messagingSenderId: '96147049865',
    projectId: 'ecommerce-app-bf2fc',
    storageBucket: 'ecommerce-app-bf2fc.appspot.com',
    iosClientId: '96147049865-umok4mkuqcahn3ko95h2vp1kp95oc67n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

}